#!/bin/bash

if [ ! -z "$BURPSUITE" ]; then
    CERT_DIR="/tmp/certificates"
    pushd $CERT_DIR
    until [ -f cert.der ]; do
        curl -ksSL "$HTTP_PROXY/cert" -o cert.der
    done 
    popd

fi

exec "$@"
