#!/bin/bash

# Verify sudo cache / create it
#sudo -v

# Build
sudo docker build . -t spindra

# Launch spindra
sudo docker run -dit --rm \
    --name spindra \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
    -v $HOME/Downloads/spindra:/data \
    --net=container:openvpn \
    wh1t3f0x/spindra:latest

# Get in container
udo docker exec -it spindra bash
