#!/bin/bash

IMAGE_NAME="wh1t3f0x/spindra:latest"

function help() {
    echo -e "
Usage: $0 [-h]

    build                       Build from local Dockerfile

optional arguments:
  -h, --help                    Show this help message and exit
  -v, --vpn                     Path to OVPN Config file
  -o, --opt                     Additional docker options
  -b, --burp                    Launch BurpSuite with spindra
"
}

function start_image() {
    RUN_ARGS=$(cat <<EOT
run -dit --rm \
-e DISPLAY=$DISPLAY \
-v /tmp/.X11-unix/:/tmp/.X11-unix/ 
EOT
)
    if [ ! -z $OPT_FILE ]; then
        OPT_FILE=$(realpath $OPT_FILE)
        if ! test -f "$OPT_FILE"; then
            echo -e "$OPT_FILE not a file"
            exit
        fi
        RUN_ARGS+=$(envsubst < $OPT_FILE)

    elif test -f  "$PWD/opt"; then
        RUN_ARGS+=$(envsubst < "$PWD/opt")
    fi

    if [ ! -z $VPN_FILE ]; then
        RUN_ARGS+=" --net=container:openvpn "
    fi


    CONTAINER_NAME="spindra"
    IMAGES=($(sudo docker ps -a --filter "name=${CONTAINER_NAME}*" --format "{{.Names}}" | sort))
    if [ "${#IMAGES[@]}" -eq 1 ]; then
        if [[ ${IMAGES[-1]} = *[0-9] ]]; then
            CONTAINER_NAME+="_$(($(echo -n ${IMAGES[-1]} | awk -F'_' '{print $NF}')+1))"
        else
           CONTAINER_NAME+="_2" 
        fi
    elif [ "${#IMAGES[@]}" -ge 2 ]; then
        CONTAINER_NAME+="_$(($(echo -n ${IMAGES[-1]} | awk -F'_' '{print $NF}')+1))"
    fi

    # Launch Burp?
    if [ ! -z $BURPSUITE ]; then
        local BURP_IMAGE="wh1t3f0x/burpsuite:latest"
        sudo docker pull $BURP_IMAGE
        sudo docker $RUN_ARGS $BURP_IMAGE
    fi

    RUN_ARGS+=" --name=$CONTAINER_NAME "

    sudo docker pull $IMAGE_NAME
    sudo docker $RUN_ARGS $IMAGE_NAME

    # Drop into container
    sudo docker exec -it $CONTAINER_NAME bash
}

function start_vpn() {
    if [ -z $VPN_FILE ]; then
        start_image
        exit
    fi

    OPENVPN_CONFIG=$(realpath $VPN_FILE)

    if ! test -f "$OPENVPN_CONFIG"; then
        echo -e "$OPENVPN_CONFIG not a file"
        exit
    fi

    if [ "$(sudo docker ps -a --format {{.Names}} --filter 'name=openvpn')" == "openvpn" ]; then
        start_image
        exit
    fi
    
    sudo docker pull quay.io/0xcaff/openvpn-client 2>&1 >/dev/null
    sudo docker run -dit --rm --cap-add=NET_ADMIN --device /dev/net/tun --name openvpn -v $OPENVPN_CONFIG:/vpn/config/config.ovpn quay.io/0xcaff/openvpn-client 2>&1 >/dev/null

    echo -e "Waiting for VPN..."
    sleep 30
    
    # Running ?
    if [ "$(sudo docker ps -a --format {{.Names}} --filter 'name=openvpn')" != "openvpn" ]; then
        echo -n "Failed to start VPN. Check $OPENVPN_CONFIG, /dev/net/tun, or possible need a reboot."
        echo -n " You can also try adding: \n pull-filter ignore \"ifconfig-ipv6 \"\npull-filter ignore \"route-ipv6 \"\n to your config."
        exit 1
    fi

    start_image
}

_main() {
    
    ps -ef | grep dockerd | grep -v grep >/dev/null
    if [[ $? -ne 0 ]]; then
        echo -e "Docker Not RUNNING!"
        exit 1
    fi

    while getopts bhv:o:-: OPT; do

        if [ $OPT = "-" ]; then
            OPT="${OPTARG%%=*}"
            OPTARG="${OPTARG#$OPT}"
            OPTARG="${OPTARG#=}"
        fi

        case "$OPT" in
            h | help )
                help "main"
                exit 0
                ;;
            b | burp )
                BURPSUITE=1
                ;;
            o | opt )
                OPT_FILE="$OPTARG"
                ;;
            v | vpn )
                VPN_FILE="$OPTARG"
                ;;
            ??* ) 
                help
                exit 1
                ;;
            \? )
                exit 1
                ;;
        esac
    done    
    shift $((OPTIND -1))

    echo "$subcommand"
    subcommand=$1; shift
    case "$subcommand" in
        build )
            docker build . -t wh1t3f0x/spindra:latest
            exit 0
            ;;
    esac

    start_vpn

    exit 0
}

if [ "$EUID" -ne 0 ]; then
    sudo -v
    _main "$@"
else
    echo -e "Do not run as root!"
    exit 1
fi

